version: '3.4'

services:
  gameservice:
    image: ${DOCKER_REGISTRY-}gameservice
    build:
      context: .
      dockerfile: GameService/Dockerfile

  healthservice:
    image: ${DOCKER_REGISTRY-}healthservice
    build:
      context: .
      dockerfile: HealthService/Dockerfile

